const PRODUCTS = {
  promos: [
    {name:"Jameson Whisky 1L",price:"₱1,050",promo:"3 bottles for only ₱2,500!",category:"promos"},
    {name:"Jim Beam 1L",price:"₱850",promo:"3 bottles for only ₱2,499!",category:"promos"},
    {name:"Alfonso 1L 3pcs promo",price:"₱900",promo:"3 bottles for only ₱900!",category:"promos"},
    {name:"Fundador 1L 3pcs promo",price:"₱900",promo:"3 bottles for only ₱900!",category:"promos"},
    {name:"Johnnie Walker Black 1L 3pcs",price:"₱3,299",promo:"3 bottles for only ₱3,299!",category:"promos"},
    {name:"Johnnie Walker Black 1L 6pcs",price:"₱6,499",promo:"6 bottles for only ₱6,499!",category:"promos"},
    {name:"Jose Cuervo Gold 1L 3pcs",price:"₱3,150",promo:"3 bottles for only ₱3,150!",category:"promos"},
    {name:"Chivas 18 700ml",price:"₱2,200",promo:"Now only ₱2,200!",category:"promos"},
    {name:"Glenfiddich 12 700ml",price:"₱2,000",promo:"Now only ₱2,000!",category:"promos"},
    {name:"Monkey Shoulder 700ml",price:"₱1,300",promo:"Now only ₱1,300!",category:"promos"},
    {name:"Dalmore 12yo 700ml",price:"₱3,500",promo:"Now only ₱3,500!",category:"promos"},
    {name:"Glenmorangie 14 700ml",price:"₱3,000",promo:"Now only ₱3,000!",category:"promos"},
    {name:"Payday Pack",price:"₱50 off/bottle",promo:"Buy any 3 bottles ₱999 & below — save ₱150 total!",category:"promos"},
    {name:"Weekend Pack",price:"₱2,499",promo:"Any 3 whisky bottles for only ₱2,499!",category:"promos"},
  ],
  whisky: [
    // Single Malt Scotch
    {name:"Aberfeldy 12 700ml",price:"₱3,199",details:"12-year Highland single malt, pear and vanilla",subcategory:"Single Malt Scotch"},
    {name:"Aberfeldy 16 700ml",price:"₱5,299",details:"16-year Highland single malt, elegant and complex",subcategory:"Single Malt Scotch"},
    {name:"Aberfeldy 21 700ml",price:"₱10,000",details:"21-year Highland single malt, luxury gift",subcategory:"Single Malt Scotch"},
    {name:"Aberlour 10 700ml",price:"₱2,499",details:"10-year Speyside single malt, fruity and smooth",subcategory:"Single Malt Scotch"},
    {name:"Aberlour 12 NCF 700ml",price:"₱3,499",details:"12-year non-chill filtered Speyside malt",subcategory:"Single Malt Scotch"},
    {name:"Aberlour 12 Double Cask 700ml",price:"₱3,399",details:"12-year double cask Speyside malt",subcategory:"Single Malt Scotch"},
    {name:"Aberlour 14 Double Cask 700ml",price:"₱4,399",details:"14-year double cask Speyside, rich and smooth",subcategory:"Single Malt Scotch"},
    {name:"Aberlour Abunadh Alba 700ml",price:"₱4,999",details:"Cask strength Speyside, sherry-forward and intense",subcategory:"Single Malt Scotch"},
    {name:"AncNoc 12 700ml",price:"₱2,499",details:"12-year Highland single malt, light and fruity",subcategory:"Single Malt Scotch"},
    {name:"Ardbeg 5 Wee Beastie",price:"₱3,099",details:"Intensely peaty and smoky Islay malt",subcategory:"Single Malt Scotch"},
    {name:"Ardbeg 10 700ml",price:"₱3,699",details:"Classic Islay 10-year, bold peat and smoke",subcategory:"Single Malt Scotch"},
    {name:"Ardbeg An Oa",price:"₱5,499",details:"Classic Islay peat and smoke",subcategory:"Single Malt Scotch"},
    {name:"Arran 10",price:"₱3,099",details:"10-year Isle of Arran single malt",subcategory:"Single Malt Scotch"},
    {name:"Arran 18",price:"₱5,499",details:"18-year Island single malt, premium gift",subcategory:"Single Malt Scotch"},
    {name:"Arran Barrel Reserve 700ml",price:"₱2,199",details:"Isle of Arran first-fill bourbon cask, fresh and sweet",subcategory:"Single Malt Scotch"},
    {name:"Arran Machrie Moor 700ml",price:"₱4,099",details:"Peated Isle of Arran single malt",subcategory:"Single Malt Scotch"},
    {name:"Arran Quarter Cask 700ml",price:"₱3,699",details:"Isle of Arran double matured in quarter casks",subcategory:"Single Malt Scotch"},
    {name:"Arran Sherry Cask 700ml",price:"₱4,399",details:"Isle of Arran finished in sherry casks, rich and spiced",subcategory:"Single Malt Scotch"},
    {name:"Ardmore Legacy 700ml",price:"₱1,599",details:"Lightly peated Highland single malt",subcategory:"Single Malt Scotch"},
    {name:"Auchentoshan Three Wood",price:"₱2,499",details:"Triple-matured Lowland single malt, rich and complex",subcategory:"Single Malt Scotch"},
    {name:"Auchentoshan American Oak 700ml",price:"₱1,699",details:"Lowland triple distilled, vanilla and coconut",subcategory:"Single Malt Scotch"},
    {name:"Auchentoshan 12 700ml",price:"₱2,099",details:"12-year Lowland triple distilled single malt",subcategory:"Single Malt Scotch"},
    {name:"Auchentoshan 21 700ml",price:"₱7,999",details:"21-year Lowland single malt, elegant and complex",subcategory:"Single Malt Scotch"},
    {name:"Aultmore 12 700ml",price:"₱3,499",details:"12-year Speyside single malt, floral and fresh",subcategory:"Single Malt Scotch"},
    {name:"Aultmore 21 700ml",price:"₱10,999",details:"21-year Speyside single malt, refined and complex",subcategory:"Single Malt Scotch"},
    {name:"Balvenie 12 Doublewood",price:"₱4,000",details:"12-year double cask Speyside, honey and vanilla",subcategory:"Single Malt Scotch"},
    {name:"Balvenie 14 Caribbean",price:"₱5,499",details:"14-year rum cask finish, tropical notes",subcategory:"Single Malt Scotch"},
    {name:"Balvenie Portwood 21 700ml",price:"₱14,999",details:"21-year Speyside finished in port pipes, exceptional",subcategory:"Single Malt Scotch"},
    {name:"Benriach 10 The Original 700ml",price:"₱2,499",details:"10-year triple matured Speyside, light and fruity",subcategory:"Single Malt Scotch"},
    {name:"Benriach 10 The Smoky Ten 700ml",price:"₱2,499",details:"10-year peated Speyside single malt",subcategory:"Single Malt Scotch"},
    {name:"Benriach 12 700ml",price:"₱2,799",details:"12-year Speyside, sweet and complex",subcategory:"Single Malt Scotch"},
    {name:"Benriach 21 700ml",price:"₱8,999",details:"21-year Speyside, deeply complex luxury single malt",subcategory:"Single Malt Scotch"},
    {name:"Bladnoch Vinaya 700ml",price:"₱2,799",details:"Lowland single malt, fresh floral and fruity character",subcategory:"Single Malt Scotch"},
    {name:"Bowmore 12",price:"₱2,499",details:"12-year balanced Islay peat malt",subcategory:"Single Malt Scotch"},
    {name:"Bruichladdich Classic Laddie 700ml",price:"₱3,499",details:"Unpeated Islay single malt, fresh and floral",subcategory:"Single Malt Scotch"},
    {name:"Bruichladdich Port Charlotte 10 700ml",price:"₱4,299",details:"Heavily peated Islay, 10-year bold and complex",subcategory:"Single Malt Scotch"},
    {name:"Bunnahabhain 12 700ml",price:"₱2,899",details:"12-year unpeated Islay, rich and nutty",subcategory:"Single Malt Scotch"},
    {name:"Caol Ila 12 700ml",price:"₱3,699",details:"12-year peated Islay, light smoke and maritime",subcategory:"Single Malt Scotch"},
    {name:"Cardhu 12 1L",price:"₱3,499",details:"12-year Speyside single malt, smooth and sweet",subcategory:"Single Malt Scotch"},
    {name:"Clynelish 14 700ml",price:"₱3,699",details:"14-year Highland coastal malt, waxy and fruity",subcategory:"Single Malt Scotch"},
    {name:"Cragganmore 12 700ml",price:"₱2,799",details:"12-year complex Speyside single malt",subcategory:"Single Malt Scotch"},
    {name:"Craigellachie 13 700ml",price:"₱3,199",details:"13-year Speyside, meaty and robust character",subcategory:"Single Malt Scotch"},
    {name:"Dalmore 12",price:"₱4,499",details:"12-year Highland malt, orange and chocolate",subcategory:"Single Malt Scotch"},
    {name:"Dalmore 12 Sherry Cask 700ml",price:"₱4,699",details:"Dalmore 12 finished in sherry casks, rich and indulgent",subcategory:"Single Malt Scotch"},
    {name:"Dalmore 15",price:"₱6,299",details:"15-year opulent Highland malt",subcategory:"Single Malt Scotch"},
    {name:"Dalmore Legacy",price:"₱3,500",details:"Rich and complex Highland single malt",subcategory:"Single Malt Scotch"},
    {name:"Dalwhinnie 15",price:"₱3,399",details:"15-year Highland malt, heather honey and vanilla",subcategory:"Single Malt Scotch"},
    {name:"Deanston 12 Sherry 700ml",price:"₱3,099",details:"12-year sherry cask Highland, sweet and nutty",subcategory:"Single Malt Scotch"},
    {name:"Deanston Heritage Sherry 700ml",price:"₱2,499",details:"Deanston sherry finish, smooth and approachable",subcategory:"Single Malt Scotch"},
    {name:"Edradour 10",price:"₱3,499",details:"10-year Highland single malt from Scotland's smallest distillery",subcategory:"Single Malt Scotch"},
    {name:"Edradour 12 700ml",price:"₱5,399",details:"12-year from Scotland's smallest distillery, rich and creamy",subcategory:"Single Malt Scotch"},
    {name:"Finlaggan Cask Strength 700ml",price:"₱2,599",details:"Cask strength Islay peated single malt",subcategory:"Single Malt Scotch"},
    {name:"FetterCairn 12 700ml",price:"₱3,099",details:"12-year Highland single malt, tropical and floral",subcategory:"Single Malt Scotch"},
    {name:"GlenAllachie 8 700ml",price:"₱3,099",details:"8-year multi-cask Speyside, rich and approachable",subcategory:"Single Malt Scotch"},
    {name:"GlenAllachie 12 700ml",price:"₱3,699",details:"12-year Speyside, sherry-forward and complex",subcategory:"Single Malt Scotch"},
    {name:"GlenDronach 12 Sherry",price:"₱3,299",details:"12-year sherry cask Highland malt",subcategory:"Single Malt Scotch"},
    {name:"GlenDronach 15 700ml",price:"₱4,799",details:"15-year sherry cask Highland, deep and rich",subcategory:"Single Malt Scotch"},
    {name:"GlenDronach Forgue 10 1L",price:"₱3,699",details:"10-year Highland single malt, fruity and approachable",subcategory:"Single Malt Scotch"},
    {name:"GlenDronach 21 700ml",price:"₱16,999",details:"21-year Parliament sherry cask, exceptional luxury",subcategory:"Single Malt Scotch"},
    {name:"GlenFarclas 10 Sherry 700ml",price:"₱2,799",details:"10-year 100% sherry cask Speyside, bold and rich",subcategory:"Single Malt Scotch"},
    {name:"GlenFarclas 15 700ml",price:"₱4,799",details:"15-year sherry cask Speyside, complex and warming",subcategory:"Single Malt Scotch"},
    {name:"GlenFarclas 105 Cask Strength 1L",price:"₱3,499",details:"Cask strength 60% ABV Speyside, powerful and rich",subcategory:"Single Malt Scotch"},
    {name:"GlenFarclas 25 700ml",price:"₱12,999",details:"25-year Speyside luxury single malt",subcategory:"Single Malt Scotch"},
    {name:"Glenfiddich 12 700ml",price:"₱2,299",srp:"₱2,899",details:"World's most awarded single malt",subcategory:"Single Malt Scotch"},
    {name:"Glenfiddich 12 Sherry 700ml",price:"₱2,899",details:"Glenfiddich 12 sherry cask edition, richer and sweeter",subcategory:"Single Malt Scotch"},
    {name:"Glenfiddich 15",price:"₱3,199",srp:"₱4,099",details:"15-year Solera system Speyside malt",subcategory:"Single Malt Scotch"},
    {name:"Glenfiddich 16 Aston Martin 700ml",price:"₱5,999",details:"16-year Glenfiddich special Aston Martin edition",subcategory:"Single Malt Scotch"},
    {name:"Glenfiddich 18 700ml",price:"₱5,499",srp:"₱6,399",details:"18-year elegant Speyside single malt",subcategory:"Single Malt Scotch"},
    {name:"Glenfiddich 18 Triple Sherry 700ml",price:"₱6,099",details:"18-year triple sherry cask Glenfiddich, rich and complex",subcategory:"Single Malt Scotch"},
    {name:"Glenfiddich 21 700ml",price:"₱10,999",details:"21-year Gran Reserva, rum cask finish",subcategory:"Single Malt Scotch"},
    {name:"Glenfiddich IPA 700ml",price:"₱3,599",details:"Glenfiddich finished in IPA craft beer casks",subcategory:"Single Malt Scotch"},
    {name:"GlenGarioch 12 700ml",price:"₱2,499",details:"12-year Highland single malt, fruity and spicy",subcategory:"Single Malt Scotch"},
    {name:"GlenGlassaugh 12 700ml",price:"₱3,499",details:"12-year coastal Highland single malt",subcategory:"Single Malt Scotch"},
    {name:"GlenGrant 12 700ml",price:"₱2,799",details:"12-year Speyside single malt, light and elegant",subcategory:"Single Malt Scotch"},
    {name:"GlenGrant 18 700ml",price:"₱5,399",details:"18-year Speyside, rare and refined",subcategory:"Single Malt Scotch"},
    {name:"Glengoyne 12 700ml",price:"₱2,999",details:"12-year unpeated Highland, sweet and approachable",subcategory:"Single Malt Scotch"},
    {name:"Glengoyne 21 700ml",price:"₱10,999",details:"21-year unpeated Highland, luxury single malt",subcategory:"Single Malt Scotch"},
    {name:"GlenkinChie 12",price:"₱2,999",details:"12-year Lowland single malt, light and floral",subcategory:"Single Malt Scotch"},
    {name:"GlenLivet 12 700ml",price:"₱2,199",details:"Original Speyside single malt",subcategory:"Single Malt Scotch"},
    {name:"GlenLivet 18 700ml",price:"₱5,999",details:"18-year Speyside, exceptionally smooth and complex",subcategory:"Single Malt Scotch"},
    {name:"GlenLivet 21 700ml",price:"₱14,999",details:"21-year archive Speyside, rare and prestigious",subcategory:"Single Malt Scotch"},
    {name:"GlenLivet Distillers Reserve 1L",price:"₱2,599",details:"Speyside single malt, smooth and versatile",subcategory:"Single Malt Scotch"},
    {name:"GlenMorangie 10 700ml",price:"₱2,099",srp:"₱2,689",details:"10-year Highland malt, vanilla and peach",subcategory:"Single Malt Scotch"},
    {name:"GlenMorangie 12 Lasanta 700ml",price:"₱2,899",details:"12-year sherry cask finish Highland, rich and sweet",subcategory:"Single Malt Scotch"},
    {name:"GlenMorangie 14 700ml",price:"₱3,499",details:"14-year extra-matured Highland malt, rich fruit and spice",subcategory:"Single Malt Scotch"},
    {name:"Glenmorangie 18 Extremely Rare 700ml",price:"₱6,599",details:"18-year Highland, exceptionally smooth and refined",subcategory:"Single Malt Scotch"},
    {name:"GlenMoray Sherry 700ml",price:"₱1,899",details:"Speyside single malt sherry finish, affordable and rich",subcategory:"Single Malt Scotch"},
    {name:"GlenMoray 12 700ml",price:"₱2,199",details:"12-year Speyside single malt, smooth and approachable",subcategory:"Single Malt Scotch"},
    {name:"GlenRothes 12 700ml",price:"₱3,199",details:"12-year Speyside, sherry and fruit forward",subcategory:"Single Malt Scotch"},
    {name:"Glen Scotia Campbeltown 700ml",price:"₱2,799",details:"Campbeltown single malt, maritime and complex",subcategory:"Single Malt Scotch"},
    {name:"GlenScotia PX Double Cask 700ml",price:"₱2,799",details:"Campbeltown double cask PX finish, rich and sweet",subcategory:"Single Malt Scotch"},
    {name:"Glenturret 10",price:"₱2,799",details:"10-year Highland single malt from Scotland's oldest distillery",subcategory:"Single Malt Scotch"},
    {name:"Glenturret Sherry Cask 700ml",price:"₱2,799",details:"Scotland's oldest distillery, sherry cask expression",subcategory:"Single Malt Scotch"},
    {name:"Ileach Cask Strength 700ml",price:"₱2,599",details:"Cask strength Islay peated single malt, bold and smoky",subcategory:"Single Malt Scotch"},
    {name:"Inchgower 14 700ml",price:"₱3,699",details:"14-year Speyside coastal single malt",subcategory:"Single Malt Scotch"},
    {name:"Jura 12 700ml",price:"₱2,199",details:"12-year Island single malt, light and approachable",subcategory:"Single Malt Scotch"},
    {name:"Jura 12 Sherry Cask",price:"₱1,800",srp:"₱2,449",details:"12-year Island malt finished in sherry casks, rich and sweet",subcategory:"Single Malt Scotch"},
    {name:"Jura 15 Sherry Cask",price:"₱2,700",details:"15-year Island malt sherry cask finish, deep and complex",subcategory:"Single Malt Scotch"},
    {name:"Knockando 12 700ml",price:"₱2,499",details:"12-year Speyside, light and elegant seasonal malt",subcategory:"Single Malt Scotch"},
    {name:"Knockando 18 700ml",price:"₱4,199",details:"18-year slow-matured Speyside single malt",subcategory:"Single Malt Scotch"},
    {name:"Lagavulin 8",price:"₱4,299",details:"8-year punchy Islay classic",subcategory:"Single Malt Scotch"},
    {name:"Lagavulin 16",price:"₱5,299",details:"16-year quintessential Islay peat malt",subcategory:"Single Malt Scotch"},
    {name:"Laphroaig 10 700ml",price:"₱3,000",srp:"₱3,135",details:"Powerful peat, seaweed and iodine Islay malt",subcategory:"Single Malt Scotch"},
    {name:"Laphroaig Quarter Cask 700ml",price:"₱2,899",details:"Laphroaig quarter cask, intense peat and vanilla",subcategory:"Single Malt Scotch"},
    {name:"Laphroaig Oak Select 700ml",price:"₱2,099",details:"Laphroaig oak select, lighter peated Islay style",subcategory:"Single Malt Scotch"},
    {name:"Ledaig 10 700ml",price:"₱2,799",details:"10-year peated Tobermory, bold and smoky Island malt",subcategory:"Single Malt Scotch"},
    {name:"Linkwood 12 700ml",price:"₱3,999",details:"12-year Speyside single malt, floral and elegant",subcategory:"Single Malt Scotch"},
    {name:"Loch Lomond 12 700ml",price:"₱3,099",details:"12-year Highland single malt, smooth and versatile",subcategory:"Single Malt Scotch"},
    {name:"Macallan 12 Double Cask 700ml",price:"₱4,499",srp:"₱6,600",details:"12-year honeyed double cask Speyside",subcategory:"Single Malt Scotch"},
    {name:"Macallan 12 Sherry Cask 700ml",price:"₱5,499",srp:"₱8,499",details:"12-year sherry cask, rich dried fruit",subcategory:"Single Malt Scotch"},
    {name:"Macallan 15 Double Cask 700ml",price:"₱9,000",details:"15-year deep complexity Speyside",subcategory:"Single Malt Scotch"},
    {name:"Macallan 18 Sherry Cask 700ml",price:"₱32,000",details:"18-year sherry cask, world class luxury",subcategory:"Single Malt Scotch"},
    {name:"Macallan Rare Cask 700ml",price:"₱23,999",details:"Rare sherry oak casks, intense dried fruit",subcategory:"Single Malt Scotch"},
    {name:"Mortlach 12 700ml",price:"₱3,399",details:"12-year 'The Wee Witchie' Speyside, meaty and rich",subcategory:"Single Malt Scotch"},
    {name:"Mortlach 16 700ml",price:"₱4,999",details:"16-year distiller's dram Speyside, deep and complex",subcategory:"Single Malt Scotch"},
    {name:"Oban 14 700ml",price:"₱4,299",details:"14-year West Highland coastal single malt",subcategory:"Single Malt Scotch"},
    {name:"Old Pulteney 12 700ml",price:"₱2,499",details:"12-year coastal Highland, salty and maritime",subcategory:"Single Malt Scotch"},
    {name:"Royal Brackla 12 700ml",price:"₱3,699",details:"12-year sherry cask Highland single malt",subcategory:"Single Malt Scotch"},
    {name:"Singleton 12",price:"₱1,850",srp:"₱2,359",details:"Sweet approachable Speyside single malt",subcategory:"Single Malt Scotch"},
    {name:"Singleton 12 Gift 700ml",price:"₱2,399",details:"Singleton 12 gift edition, smooth and approachable",subcategory:"Single Malt Scotch"},
    {name:"Singleton 12 Glen Ord Sherry Finish 700ml",price:"₱3,099",details:"Singleton sherry finish, sweeter and richer style",subcategory:"Single Malt Scotch"},
    {name:"Singleton 15 700ml",price:"₱3,499",details:"15-year Singleton, smooth and mellow",subcategory:"Single Malt Scotch"},
    {name:"Singleton 18 700ml",price:"₱5,999",details:"18-year Singleton, rich and complex",subcategory:"Single Malt Scotch"},
    {name:"Singleton 21 700ml",price:"₱10,999",details:"21-year Singleton, exceptional aged single malt",subcategory:"Single Malt Scotch"},
    {name:"Singleton 25 700ml",price:"₱26,999",details:"25-year ultra-premium Singleton, rare luxury",subcategory:"Single Malt Scotch"},
    {name:"Speyburn 10 700ml",price:"₱1,499",details:"10-year Speyside single malt, fresh and affordable",subcategory:"Single Malt Scotch"},
    {name:"Speyburn 16 1L",price:"₱3,699",details:"16-year Speyside 1L, great value single malt",subcategory:"Single Malt Scotch"},
    {name:"Speymhor 12 700ml",price:"₱2,999",details:"12-year Speyside single malt, smooth and fruity",subcategory:"Single Malt Scotch"},
    {name:"Talisker 10 700ml",price:"₱3,099",details:"Isle of Skye classic, peppery and smoky",subcategory:"Single Malt Scotch"},
    {name:"Talisker Skye 700ml",price:"₱2,999",details:"Talisker Skye, lighter and more approachable Island malt",subcategory:"Single Malt Scotch"},
    {name:"Talisker Storm 700ml",price:"₱3,099",details:"Talisker Storm, bold maritime and peated character",subcategory:"Single Malt Scotch"},
    {name:"Tamdhu 12 700ml",price:"₱3,099",details:"12-year 100% sherry cask Speyside, rich and smooth",subcategory:"Single Malt Scotch"},
    {name:"Tamdhu 15 700ml",price:"₱6,599",details:"15-year Speyside sherry matured, deep and complex",subcategory:"Single Malt Scotch"},
    {name:"Tamnavulin Double Cask 700ml",price:"₱1,899",details:"Speyside double cask, affordable and smooth",subcategory:"Single Malt Scotch"},
    {name:"Tamnavulin Sherry Cask 700ml",price:"₱1,899",details:"Speyside sherry cask finish, sweet and approachable",subcategory:"Single Malt Scotch"},
    // Blended Scotch
    {name:"Ballantine's Finest 700ml",price:"₱850",details:"Smooth blended Scotch whisky",subcategory:"Blended Scotch"},
    {name:"Ballantine's Finest 1L",price:"₱950",details:"Smooth blended Scotch whisky",subcategory:"Blended Scotch"},
    {name:"Ballantines 2L",price:"₱1,800",details:"Classic blended Scotch whisky large format",subcategory:"Blended Scotch"},
    {name:"Ballantines 12 yrs",price:"₱1,300",details:"12-year blended Scotch whisky",subcategory:"Blended Scotch"},
    {name:"Ballantines Finest 3L",price:"₱2,999",details:"Smooth blended Scotch whisky large format",subcategory:"Blended Scotch"},
    {name:"Ballantines Finest 21 Years 700ml",price:"₱5,999",details:"21-year premium blended Scotch whisky",subcategory:"Blended Scotch"},
    {name:"Burn Mckenzie 700ml",price:"₱599",details:"Smooth blended Scotch whisky, great value",subcategory:"Blended Scotch"},
    {name:"Charles and James Light 1L",price:"₱599",details:"Light blended Scotch whisky",subcategory:"Blended Scotch"},
    {name:"Chivas 12",price:"₱999",srp:"₱1,099",details:"12-year smooth blended Scotch whisky",subcategory:"Blended Scotch"},
    {name:"Chivas 18",price:"₱2,300",srp:"₱2,969",details:"18-year rich and luxurious blended Scotch",subcategory:"Blended Scotch"},
    {name:"Claymore 700ml",price:"₱599",details:"Smooth blended Scotch whisky",subcategory:"Blended Scotch"},
    {name:"Copper Dog 700ml",price:"₱1,499",details:"Speyside blended malt whisky, fruity and smooth",subcategory:"Blended Scotch"},
    {name:"Cutty Sark 700ml",price:"₱599",details:"Light and smooth blended Scotch",subcategory:"Blended Scotch"},
    {name:"Cutty Sark 1.75L",price:"₱1,399",details:"Light blended Scotch large format",subcategory:"Blended Scotch"},
    {name:"Dewars 8 Portugese Smooth",price:"₱1,299",details:"8-year Scotch finished in Portuguese casks",subcategory:"Blended Scotch"},
    {name:"Dewars 8 Japanese Smooth",price:"₱1,299",details:"8-year Scotch finished in Japanese casks",subcategory:"Blended Scotch"},
    {name:"Dewars 8 Carribean Smooth",price:"₱1,299",details:"8-year Scotch finished in Caribbean casks",subcategory:"Blended Scotch"},
    {name:"Dewars 12 1L",price:"₱1,450",details:"12-year blended Scotch whisky large format",subcategory:"Blended Scotch"},
    {name:"Dewars 15 700ml",price:"₱1,999",details:"15-year blended Scotch, smooth and honeyed",subcategory:"Blended Scotch"},
    {name:"Dewars 18 700ml",price:"₱3,499",details:"18-year blended Scotch, complex and refined",subcategory:"Blended Scotch"},
    {name:"Famous Grouse 700ml",price:"₱1,049",details:"Scotland's favourite blended Scotch whisky",subcategory:"Blended Scotch"},
    {name:"Famous Grouse Smoky Black 700ml",price:"₱1,299",details:"Smoky blended Scotch with Islay malt influence",subcategory:"Blended Scotch"},
    {name:"Famous Grouse 12 700ml",price:"₱1,599",details:"12-year Famous Grouse, richer and more complex",subcategory:"Blended Scotch"},
    {name:"Grand Old Parr 12",price:"₱1,999",details:"12-year premium blended Scotch whisky",subcategory:"Blended Scotch"},
    {name:"Grants Triple Wood 700ml",price:"₱799",details:"Triple wood blended Scotch, smooth and affordable",subcategory:"Blended Scotch"},
    {name:"Greign 20 Years Old",price:"₱2,199",details:"20-year aged blended whisky",subcategory:"Blended Scotch"},
    {name:"Harrier 700ml",price:"₱599",details:"Smooth blended Scotch whisky",subcategory:"Blended Scotch"},
    {name:"Isle of Skye 21 700ml",price:"₱5,999",details:"21-year aged blended Scotch, rich and complex",subcategory:"Blended Scotch"},
    {name:"JG Kinsey 700ml",price:"₱599",details:"Smooth blended Scotch whisky",subcategory:"Blended Scotch"},
    {name:"Johnnie Walker Red Label 700ml",price:"₱899",details:"Johnnie Walker Red Label, classic blended Scotch",subcategory:"Blended Scotch"},
    {name:"Johnnie Walker Red Label 1L",price:"₱1,049",details:"Johnnie Walker Red Label 1L",subcategory:"Blended Scotch"},
    {name:"Johnnie Walker Black 1L",price:"₱1,199",srp:"₱1,499",details:"12-year iconic smoky blended Scotch",subcategory:"Blended Scotch"},
    {name:"Johnnie Walker Double Black 700ml",price:"₱1,399",srp:"₱1,499",details:"Intensified smoky blended Scotch",subcategory:"Blended Scotch"},
    {name:"Johnnie Walker Double Black 1L",price:"₱2,199",details:"Johnnie Walker Double Black 1L large format",subcategory:"Blended Scotch"},
    {name:"Johnnie Walker Gold Label",price:"₱2,299",details:"18-year blended Scotch, honeyed and smooth",subcategory:"Blended Scotch"},
    {name:"Johnnie Walker Gold Reserve 750ml",price:"₱2,499",details:"Johnnie Walker Gold Reserve 750ml",subcategory:"Blended Scotch"},
    {name:"Johnnie Walker Ruby 700ml",price:"₱1,999",details:"Johnnie Walker Ruby, smooth and rich",subcategory:"Blended Scotch"},
    {name:"Johnnie Walker Ruby 1L",price:"₱2,499",details:"Johnnie Walker Ruby 1L large format",subcategory:"Blended Scotch"},
    {name:"Johnnie Walker 15 700ml",price:"₱2,899",details:"Johnnie Walker 15-year aged, smooth and refined",subcategory:"Blended Scotch"},
    {name:"Johnnie Walker Blue Label 700ml",price:"₱6,500",details:"Rare blended Scotch, smooth and prestigious",subcategory:"Blended Scotch"},
    {name:"John Walker and Sons XR 21 750ml",price:"₱5,999",details:"John Walker XR 21-year, prestigious blend",subcategory:"Blended Scotch"},
    {name:"Johnnie Walker King George V 750ml",price:"₱22,999",details:"Johnnie Walker King George V, ultra-luxury rare blend",subcategory:"Blended Scotch"},
    {name:"Monkey Shoulder",price:"₱1,500",srp:"₱2,249",details:"Triple malt blended Scotch, smooth and creamy",subcategory:"Blended Scotch"},
    {name:"Naked Malt Sherry 700ml",price:"₱1,799",details:"Sherry cask blended malt, smooth and approachable",subcategory:"Blended Scotch"},
    {name:"Royal Salute 21",price:"₱5,999",details:"21-year Scotland's most prestigious blend",subcategory:"Blended Scotch"},
    {name:"Royal Salute 21 Blended Grain 750ml",price:"₱5,999",details:"21-year Royal Salute blended grain expression",subcategory:"Blended Scotch"},
    {name:"Three Scottish Brothers 20 years old",price:"₱1,999",details:"20-year aged blended Scotch whisky",subcategory:"Blended Scotch"},
    {name:"Vat 69 700ml",price:"₱599",details:"Classic blended Scotch whisky",subcategory:"Blended Scotch"},
    {name:"Whyte and Mackay 700ml",price:"₱599",details:"Smooth blended Scotch whisky",subcategory:"Blended Scotch"},
    {name:"Wildmoor Heather Valley 21 700ml",price:"₱6,199",details:"21-year aged blended Scotch, smooth and complex",subcategory:"Blended Scotch"},
    // Irish
    {name:"Jameson Whisky 1L",price:"₱999",srp:"₱1,499",details:"World's best-selling Irish whiskey",subcategory:"Irish"},
    {name:"Tullamore Dew Irish Whiskey",price:"₱1,200",details:"Triple-distilled smooth Irish whiskey",subcategory:"Irish"},
    {name:"Bushmills Original 700ml",price:"₱1,049",details:"Classic Irish whiskey, smooth and light",subcategory:"Irish"},
    // Japanese
    {name:"Hibiki Harmony",price:"₱6,499",srp:"₱9,400",details:"Masterfully blended Japanese whisky",subcategory:"Japanese"},
    {name:"Yamazaki Single Malt",price:"₱6,999",details:"Japan's most celebrated single malt",subcategory:"Japanese"},
    {name:"Suntory Hakushu 700ml",price:"₱6,499",details:"Fresh peated Japanese single malt",subcategory:"Japanese"},
    {name:"Suntory Ao 700ml",price:"₱3,999",details:"World blend from 5 countries, smooth and elegant",subcategory:"Japanese"},
    {name:"Suntory Royal 700ml",price:"₱3,099",details:"Classic Japanese blended whisky by Suntory",subcategory:"Japanese"},
    {name:"Suntory Old Whisky 700ml",price:"₱1,999",details:"Classic Japanese blended whisky",subcategory:"Japanese"},
    {name:"The Chita - Distiller's Reserve",price:"₱2,799",details:"Smooth grain Japanese whisky from the Chita distillery",subcategory:"Japanese"},
    {name:"The Tottori - Ex Bourbon Barrel",price:"₱1,799",details:"Japanese blended malt aged in bourbon barrels",subcategory:"Japanese"},
    {name:"The San In Japanese Whisky",price:"₱1,500",details:"Smooth Japanese blended whisky",subcategory:"Japanese"},
    {name:"Kakubin Yellow Label",price:"₱1,250",details:"Classic Japanese blended whisky",subcategory:"Japanese"},
    {name:"Tenjaku Whisky",price:"₱1,499",details:"Smooth and light Japanese blended whisky",subcategory:"Japanese"},
    {name:"Nikka Coffey Malt Whisky",price:"₱3,499",details:"Rich fruity Japanese whisky",subcategory:"Japanese"},
    {name:"Nikka Coffey Grain 700ml",price:"₱3,399",details:"Japanese grain whisky, sweet and creamy",subcategory:"Japanese"},
    {name:"Nikka From the Barrel 500ml",price:"₱2,499",details:"Cask strength Japanese blended whisky, bold",subcategory:"Japanese"},
    {name:"Nikka Yoichi 700ml",price:"₱4,199",details:"Peated Highland-style Japanese single malt",subcategory:"Japanese"},
    {name:"Nikka Miyagikyo 700ml",price:"₱4,199",details:"Unpeated Lowland-style Japanese single malt",subcategory:"Japanese"},
    {name:"Nikka Tailored 700ml",price:"₱4,799",details:"Nikka premium blended Japanese whisky",subcategory:"Japanese"},
    {name:"Nikka Taketsuru 700ml",price:"₱4,799",details:"Pure malt Japanese whisky, complex and balanced",subcategory:"Japanese"},
    {name:"Nikka Black Clear Japanese Whisky",price:"₱1,050",details:"Smooth and light Japanese blended whisky",subcategory:"Japanese"},
    {name:"Nikka Black Special Japanese Whisky",price:"₱1,499",details:"Rich and smooth Japanese blended whisky",subcategory:"Japanese"},
    {name:"Nikka Super rare Old 700ml",price:"₱2,399",details:"Rare aged Japanese blended whisky",subcategory:"Japanese"},
    {name:"Kavalan Distillery Select No.1 700ml",price:"₱2,899",details:"Taiwanese single malt, rich tropical fruit",subcategory:"Japanese"},
    {name:"Kavalan Distillery Select No.2 700ml",price:"₱2,899",details:"Taiwanese single malt, ex-bourbon cask expression",subcategory:"Japanese"},
    // American/Bourbon
    {name:"Jack Daniel's No.7 1L",price:"₱1,599",srp:"₱1,680",details:"Iconic charcoal-mellowed Tennessee whiskey",subcategory:"American & Bourbon"},
    {name:"Jack Daniels No.7 700ml",price:"₱1,399",details:"Iconic charcoal-mellowed Tennessee whiskey 700ml",subcategory:"American & Bourbon"},
    {name:"Jack Daniels No.7 1.5L",price:"₱2,499",details:"Jack Daniel's No.7 1.5L large format",subcategory:"American & Bourbon"},
    {name:"Jack Daniels No.7 3L",price:"₱5,299",details:"Jack Daniel's No.7 3L party format",subcategory:"American & Bourbon"},
    {name:"Jack Daniel's Gentleman Jack",price:"₱1,499",details:"Double mellowed premium Tennessee whiskey",subcategory:"American & Bourbon"},
    {name:"Jack Daniel's Sweet & Oaky",price:"₱1,999",details:"Tennessee whiskey with sweet oak notes",subcategory:"American & Bourbon"},
    {name:"Jack Daniel's Bold & Spicy",price:"₱1,999",details:"Tennessee whiskey with bold spicy character",subcategory:"American & Bourbon"},
    {name:"Jack Daniels Honey 700ml",price:"₱1,299",details:"Jack Daniel's Tennessee Honey, smooth and sweet",subcategory:"American & Bourbon"},
    {name:"Jack Daniels Apple 700ml",price:"₱1,299",details:"Jack Daniel's Tennessee Apple, crisp and refreshing",subcategory:"American & Bourbon"},
    {name:"Jack Daniels Red Dog Saloon 700ml",price:"₱1,699",details:"Jack Daniel's Red Dog Saloon limited edition",subcategory:"American & Bourbon"},
    {name:"Jim Beam 1L",price:"₱850",srp:"₱1,039",details:"Classic Kentucky straight bourbon large format",subcategory:"American & Bourbon"},
    {name:"Jim Beam 750ml",price:"₱899",details:"Classic Kentucky straight bourbon",subcategory:"American & Bourbon"},
    {name:"Jim Beam Apple 700ml",price:"₱1,049",details:"Jim Beam with natural apple flavour",subcategory:"American & Bourbon"},
    {name:"Jim Beam Honey 700ml",price:"₱899",details:"Jim Beam with natural honey flavour",subcategory:"American & Bourbon"},
    {name:"Woodford Reserve 1L",price:"₱2,599",details:"Premium small batch Kentucky Bourbon",subcategory:"American & Bourbon"},
    {name:"Woodford Reserve Rye 1L",price:"₱2,999",details:"Premium Kentucky straight rye whiskey 1L",subcategory:"American & Bourbon"},
    {name:"Bulleit Bourbon 1L",price:"₱1,799",details:"High-rye Kentucky Bourbon",subcategory:"American & Bourbon"},
    {name:"1792 Small Batch",price:"₱2,299",details:"Award-winning Kentucky straight bourbon",subcategory:"American & Bourbon"},
    {name:"Eagle Rare 10 750ml",price:"₱2,799",details:"10-year single barrel Kentucky bourbon, bold and complex",subcategory:"American & Bourbon"},
    {name:"Evan Williams Black 750ml",price:"₱899",details:"Affordable Kentucky straight bourbon",subcategory:"American & Bourbon"},
    {name:"Evan Williams Bottled in Bond 750ml",price:"₱1,299",details:"100-proof bottled in bond Kentucky bourbon",subcategory:"American & Bourbon"},
    {name:"Four Roses Single Barrel 700ml",price:"₱2,899",details:"Single barrel Kentucky bourbon, bold and complex",subcategory:"American & Bourbon"},
    {name:"Four Roses Small Batch 700ml",price:"₱2,599",details:"Small batch Kentucky bourbon, smooth and balanced",subcategory:"American & Bourbon"},
    {name:"Quality House White Bourbon 750ml",price:"₱849",details:"Affordable white bourbon whiskey",subcategory:"American & Bourbon"},
    {name:"Seagrams VO 700ml",price:"₱1,249",details:"Canadian blended whisky, smooth and light",subcategory:"American & Bourbon"},
  ],
  gin: [
    {name:"Hendricks",price:"₱2,750",srp:"₱2,999",details:"Floral gin with cucumber and rose"},
    {name:"Tanqueray London Gin 700ml",price:"₱899",srp:"₱1,060",details:"Classic London Dry for gin and tonics"},
    {name:"Tanqueray Sevilla 1L",price:"₱1,200",details:"Spanish orange gin, perfect for summer cocktails"},
    {name:"Bombay Sapphire",price:"₱1,099",details:"10-botanical smooth gin"},
    {name:"Sipsmith London Dry Gin",price:"₱1,399",details:"Handcrafted London Dry Gin with juniper and citrus"},
    {name:"Bulldog London Dry Gin 700ml",price:"₱1,120",details:"12-botanical bold gin"},
    {name:"Gunpowder Irish Gin 700ml",price:"₱2,590",details:"Aromatic craft Irish gin"},
    {name:"Suntory Sui Gin 700ml",price:"₱1,049",details:"Japanese gin with yuzu and cherry blossom"},
    {name:"Suntory Roku Gin 700ml",price:"₱1,999",details:"Premium Japanese gin with 6 unique botanicals"},
    {name:"Beefeater London Dry Gin 700ml",price:"₱799",details:"Classic London Dry Gin, crisp and refreshing"},
    {name:"Ginebra San Miguel 1L",price:"₱240",details:"Classic Philippine gin, smooth and light"},
    {name:"Ginebra San Miguel 700ml",price:"₱180",details:"Classic Philippine gin, smooth and light"},
    {name:"GSM Blue Premium Gin 700ml",price:"₱280",details:"Premium Philippine gin blend, smooth and bold"},
    {name:"GSM Blue Light Gin 700ml",price:"₱170",details:"Light and easy-drinking Philippine gin"},
    {name:"GSM Blue Mojito 700ml",price:"₱150",details:"Refreshing mojito-flavored gin"},
    {name:"GSM Blue Mojito 1L",price:"₱160",details:"Refreshing mojito-flavored gin large format"},
    {name:"GSM Blue Margarita 700ml",price:"₱170",details:"Margarita-flavored gin, fun and fruity"},
    {name:"GSM Blue Pomelo 700ml",price:"₱170",details:"Pomelo-flavored Philippine gin"},
    {name:"Gilbey's London Dry Gin 700ml",price:"₱299",details:"Classic London Dry Gin, crisp and clean"},
    {name:"Gilbey's Pink Gin 700ml",price:"₱299",details:"Pink gin with berry notes, smooth and fruity"},
    {name:"Primera Gin 1L",price:"₱469",details:"Premium Philippine gin, bold and refreshing"},
    {name:"The Bar Premium Grapefruit Gin 700ml",price:"₱150",details:"Grapefruit-infused premium gin"},
    {name:"The Bar Premium Greengrape Gin 700ml",price:"₱150",details:"Greengrape-infused premium gin"},
  ],
  vodka: [
    {name:"Belvedere",price:"₱2,590",details:"Premium Polish rye vodka"},
    {name:"Grey Goose",price:"₱2,310",srp:"₱2,599",details:"Premium French wheat vodka"},
    {name:"Absolut Vodka 1L",price:"₱999",srp:"₱1,099",details:"Iconic Swedish vodka"},
    {name:"Smirnoff Vodka",price:"₱800",details:"Smooth and versatile vodka"},
    {name:"Platinum Vodka 7x 1.75L",price:"₱949",details:"7x distilled vodka, large format great value"},
    {name:"Stoli Vodka 700ml",price:"₱799",details:"Classic Stolichnaya Russian vodka, clean and smooth"},
    {name:"Gilbey's Vodka 700ml",price:"₱299",details:"Clean and smooth vodka, great for cocktails"},
    {name:"Gilbey's Vodka 1L",price:"₱399",details:"Clean and smooth vodka large format"},
    {name:"Antonov Vodka 700ml",price:"₱299",details:"Smooth and affordable vodka, great for mixing"},
  ],
  brandy: [
    {name:"Fundador Special 1L",price:"₱300",details:"Classic Spanish brandy, smooth and affordable"},
    {name:"Alfonso Brandy 1L",price:"₱350",details:"Smooth brandy, great for cocktails and gifting"},
    {name:"Alfonso Light Sherry 1L",price:"₱399",details:"Light sherry-style brandy, smooth and affordable"},
    {name:"Alfonso Light 1.75L",price:"₱749",details:"Alfonso Light Brandy large format, great value"},
    {name:"Alfonso Light 500ml",price:"₱210",details:"Alfonso Light Brandy small format"},
    {name:"Alfonso Zero 1L",price:"₱399",details:"Alfonso Zero sugar brandy, smooth and light"},
    {name:"Alfonso Solera 1.75L",price:"₱1,049",details:"Alfonso Solera premium brandy large format"},
    {name:"Alfonso Solera 1L",price:"₱549",details:"Alfonso Solera premium brandy"},
    {name:"Sherry Oak 1L",price:"₱449",details:"Alfonso Sherry Oak brandy, smooth and rich"},
    {name:"Escobar Light 700ml",price:"₱220",details:"Light and smooth brandy, easy to drink"},
    {name:"Emperador 1.5L",price:"₱419",details:"Emperador Deluxe brandy large format"},
    {name:"Emperador 1L",price:"₱229",details:"Emperador Deluxe brandy, smooth and affordable"},
    {name:"Emperador 750ml",price:"₱120",details:"Emperador brandy compact size"},
    {name:"Emperador 500ml",price:"₱175",details:"Emperador brandy medium format"},
    {name:"Emperador 375ml",price:"₱90",details:"Emperador brandy small format"},
  ],
  wine: [
    {name:"Yellow Tail Cabernet Sauvignon",price:"₱629",details:"Rich blackcurrant Australian red wine"},
    {name:"Yellow Tail Moscato",price:"₱629",details:"Sweet floral Australian white wine"},
    {name:"Yellow Tail Shiraz",price:"₱629",details:"Blackberry and plum Australian red wine"},
    {name:"Yellow Tail Red Moscato 750ml",price:"₱649",details:"Sweet red moscato, fruity and easy drinking"},
    {name:"Yellow Tail Pink Moscato 750ml",price:"₱649",details:"Sweet pink moscato, floral and refreshing"},
    {name:"Yellow Tail Chardonnay 750ml",price:"₱649",details:"Crisp Australian chardonnay, fresh and smooth"},
    {name:"Yellow Tail Merlot 750ml",price:"₱649",details:"Smooth Australian merlot, plum and cherry notes"},
    {name:"Lindelman's Premiere Selection",price:"₱399",details:"Crisp and refreshing Australian white wine blend"},
    {name:"Rawson Retreat Semillon Blanc",price:"₱399",details:"Light and citrusy Australian white wine"},
    {name:"Carlo Rossi Cabernet Sauvignon 750ml",price:"₱419",details:"Rich full-bodied California red wine"},
    {name:"Carlo Rossi Merlot 750ml",price:"₱419",details:"Smooth and fruit-forward California red wine"},
    {name:"Carlo Rossi Sangria 750ml",price:"₱419",details:"Fruity and refreshing California sangria"},
    {name:"Carlo Rossi Sweet Red 750ml",price:"₱419",details:"Sweet and smooth California red wine"},
    {name:"Carlo Rossi Red Moscato 750ml",price:"₱419",details:"Sweet California red moscato"},
    {name:"Barefoot Pinot Grigio 750ml",price:"₱579",details:"Crisp California white wine with citrus notes"},
    {name:"Barefoot Cabernet Sauvignon 750ml",price:"₱579",details:"Rich California cabernet with dark fruit notes"},
    {name:"Gato Negro Malbec 750ml",price:"₱459",details:"Chilean Malbec, bold and full-bodied"},
    {name:"Gato Negro Merlot 750ml",price:"₱459",details:"Chilean Merlot, smooth and fruity"},
    {name:"Gato Negro Cabernet Sauvignon 750ml",price:"₱459",details:"Chilean Cabernet Sauvignon, rich and robust"},
    {name:"Novelino Sangria 750ml",price:"₱349",details:"Fruity and refreshing Italian-style sangria"},
    {name:"Novelino Sparkling Strawberry 750ml",price:"₱299",details:"Sweet sparkling strawberry wine"},
    {name:"Novelino Wild BlackBerry 750ml",price:"₱299",details:"Sweet sparkling wild blackberry wine"},
    {name:"Novelino Rosso Tradizionale 750ml",price:"₱360",details:"Classic Italian-style red wine"},
    {name:"Novelino Rosso Classico 750ml",price:"₱360",details:"Classic Italian-style red wine blend"},
    {name:"Novelino Bianco Classico 750ml",price:"₱360",details:"Classic Italian-style white wine"},
    {name:"Vino Fontana Sweet Red 750ml",price:"₱360",details:"Sweet and fruity red wine"},
    {name:"Vino Fontana Red 750ml",price:"₱320",details:"Smooth and easy-drinking red wine"},
    {name:"Pegeos Medium Sweet Red 750ml",price:"₱320",details:"Medium-sweet red wine, light and refreshing"},
    {name:"Pegeos Medium Sweet White 750ml",price:"₱320",details:"Medium-sweet white wine, crisp and refreshing"},
    {name:"Sangria Maria Clara 750ml",price:"₱270",details:"Classic Spanish-style sangria, fruity and fun"},
    {name:"Luis Felipe Edwards Cabernet Sauvignon",price:"₱435",details:"Chilean Cabernet Sauvignon, bold and balanced"},
    {name:"Luis Felipe Edwards Merlot",price:"₱435",details:"Chilean Merlot, smooth and round"},
    {name:"Moet & Chandon Brut",price:"₱4,000",details:"Apple, pear and brioche celebration champagne"},
  ],
  tequila: [
    {name:"Don Julio 1942",price:"₱8,999",details:"Ultra-premium aged tequila"},
    {name:"Don Julio Reposado",price:"₱4,000",details:"Dark chocolate and vanilla tequila"},
    {name:"Don Julio Anejo",price:"₱3,599",srp:"₱4,249",details:"Aged tequila with rich caramel and chocolate notes"},
    {name:"Don Julio Blanco 750ml",price:"₱3,399",details:"Premium Don Julio blanco, fresh and citrusy"},
    {name:"Patron Silver",price:"₱3,380",details:"Handcrafted small batch tequila"},
    {name:"Patron Reposado",price:"₱4,120",details:"Oak-rested premium tequila"},
    {name:"Clase Azul Reposado",price:"₱13,000",details:"Luxury tequila in ceramic decanter"},
    {name:"1800 Reposado",price:"₱2,000",details:"Caramel and spice aged tequila"},
    {name:"1800 Silver Blanco 750ml",price:"₱1,599",details:"Crystal clear premium blanco tequila"},
    {name:"1800 Anejo 750ml",price:"₱2,499",details:"Aged 1800 tequila, smooth with vanilla and oak"},
    {name:"Jose Cuervo Gold 700ml",price:"₱899",details:"Affordable tequila for cocktails"},
    {name:"Jose Cuervo Gold 1L",price:"₱1,099",srp:"₱1,240",details:"Affordable tequila for cocktails, large format"},
    {name:"Jose Cuervo Silver 700ml",price:"₱1,049",details:"Jose Cuervo silver tequila, smooth and versatile"},
    {name:"Olmeca Tequila 700ml",price:"₱899",details:"Smooth silver tequila for cocktails"},
    {name:"Cazadores 700ml",price:"₱1,699",details:"100% blue agave blanco tequila, crisp and clean"},
    {name:"Se Busca Mezcal Artesanal",price:"₱1,799",details:"Artisanal smoky mezcal from Oaxaca, Mexico"},
  ],
  cognac: [
    {name:"Hennessy VS",price:"₱1,999",srp:"₱2,309",details:"Bold fruit and toasted oak cognac"},
    {name:"Hennessy VSOP 700ml",price:"₱4,199",details:"Hennessy VSOP, smooth and elegant aged cognac"},
    {name:"Hennessy XO",price:"₱13,999",details:"Luxury cognac with candied fruit and cocoa"},
    {name:"Martell VSOP",price:"₱3,000",srp:"₱3,599",details:"Plum, honey and vanilla cognac"},
    {name:"Martel Cordon Bleu",price:"₱5,500",details:"Iconic prestigious cognac blend"},
    {name:"Remy Martin XO",price:"₱7,500",details:"Exceptional aged cognac, rich and complex"},
  ],
  rum: [
    {name:"Bacardi Gold 750ml",price:"₱849",details:"Golden rum aged in charred oak barrels, smooth and rich"},
    {name:"Bacardi Silver 750ml",price:"₱849",details:"White rum, light and clean — perfect for cocktails"},
    {name:"Captain Morgan 750ml",price:"₱649",details:"Original spiced rum, warm and smooth with a hint of vanilla"},
  ],
  liqueur: [
    {name:"Baileys",price:"₱899",details:"Irish cream dessert liqueur"},
    {name:"Jagermeister 700ml",price:"₱899",srp:"₱979",details:"Bold herbal shots liqueur"},
    {name:"Cointreau",price:"₱1,500",srp:"₱1,649",details:"Orange liqueur for cocktails"},
    {name:"Disaronno Originale",price:"₱1,099",details:"Classic Italian amaretto"},
    {name:"Disaronno Velvet",price:"₱1,299",details:"Smooth cream amaretto liqueur"},
    {name:"Tequila Rose 700ml",price:"₱1,299",details:"Strawberry cream tequila liqueur, sweet and fun"},
  ],
  soju: [
    {name:"Chingu Soju Greengrape 360ml",price:"₱120",details:"Korean-style greengrape flavored soju"},
    {name:"Chingu Soju Original 360ml",price:"₱120",details:"Korean-style original soju, clean and smooth"},
    {name:"Chingu Soju Kyoho Grape 360ml",price:"₱129",details:"Korean-style Kyoho grape flavored soju"},
    {name:"Chingu Soju Melon 360ml",price:"₱129",details:"Korean-style melon flavored soju"},
    {name:"Chingu Soju Coffee 360ml",price:"₱129",details:"Korean-style coffee flavored soju"},
    {name:"Chingu Soju Watermelon 360ml",price:"₱129",details:"Korean-style watermelon flavored soju"},
    {name:"Vino Soju Grapefruit 360ml",price:"₱120",details:"Grapefruit flavored soju, light and citrusy"},
    {name:"Vino Soju Strawberry 360ml",price:"₱120",details:"Strawberry flavored soju, sweet and smooth"},
  ],
  beer: [
    {name:"Budweiser 330ml",price:"₱50",details:"Classic American lager, crisp and refreshing"},
    {name:"Budweiser 330ml Box of 24",price:"₱1,200",details:"Budweiser 330ml 24-bottle box, great for parties"},
  ],
};

const CATEGORY_LABELS = {
  promos:  "🔥 Promos & Bundles",
  whisky:  "🥃 Whisky",
  gin:     "🌿 Gin",
  vodka:   "🫧 Vodka",
  brandy:  "🍂 Brandy",
  wine:    "🍷 Wine",
  tequila: "🌵 Tequila",
  cognac:  "✨ Cognac",
  rum:     "🏝️ Rum",
  liqueur: "🍬 Liqueur",
  soju:    "🇰🇷 Soju",
  beer:    "🍺 Beer",
};

const WHISKY_SUBCATEGORIES = ["Single Malt Scotch","Blended Scotch","Irish","Japanese","American & Bourbon"];

const SHOP = {
  name: "Sip Twice",
  location: "Mandaluyong City, Metro Manila",
  contact: "09560847104",
  facebook: "https://www.facebook.com/profile.php?id=461074500421635",
  messenger: "https://m.me/461074500421635",
  viber: "viber://chat?number=%2B639560847104",
  viber_community: "https://invite.viber.com/?g2=AQBDzlc3gQVeW1OmRwA6sR3mK1F%2FHCGGMUUf%2B86vvUArJSRankadAEcp07j%2BQKpZ",
  delivery: "FREE delivery Metro Manila on orders ₱3,000+ | Below ₱3,000: starts at ₱150",
};
